<!--
<article class="forum-post" id="forum-post-<?php //$post->getId(); ?>">
    <div class="meta">
        <a href="" class="author"><?php //$post->getAuthorDisplayName(); ?></a>
        <time datetime="<?php //$post->getSentAt()->format('c'); ?>">
            <?php //$this->dateFormat($post->getSentAt(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM); ?>
        </time>
    </div>

    <div class="content">
        <?php //$post->getContent(); ?>
    </div>
</article>-->

<div data-ng-controller="PostDetailController">
    <p>{{ remaining() }}</p>
</div>