<?php $this->headMeta()->appendName('fragment', '!'); ?>

<div data-ng-app="ForumApplication">
    <div data-ng-view></div>
</div>

<?php $this->inlineScript()->appendFile('//ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.min.js')
                           ->appendFile('//ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular-resource.min.js')
                           ->appendFile($this->basePath() . '/app/application/application.js')
                           ->appendFile($this->basePath() . '/app/categories/categories-controller.js'); ?>